/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alerts/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Alerts Disable */
        post: operations["alerts_disable_api_alerts_disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Alerts Enable
         * @description Give this account its own private ntfy topic (unguessable; the link in Settings is the subscription).
         */
        post: operations["alerts_enable_api_alerts_enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Alerts Test
         * @description One real push to your own topic, so you can see that your phone receives them.
         */
        post: operations["alerts_test_api_alerts_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Credentials
         * @description Set or change your own username and password; your other sessions are signed out.
         */
        put: operations["set_credentials_api_auth_credentials_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_config_profile_get"];
        /** Put Profile */
        put: operations["put_profile_api_config_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_api_config_watchlist_get"];
        /** Put Watchlist */
        put: operations["put_watchlist_api_config_watchlist_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instagram/relay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Relay Instagram */
        post: operations["relay_instagram_api_instagram_relay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunities */
        get: operations["list_opportunities_api_opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opp_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opportunity */
        get: operations["get_opportunity_api_opportunities__opp_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Opportunity */
        patch: operations["update_opportunity_api_opportunities__opp_id__patch"];
        trace?: never;
    };
    "/api/sources/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources Health */
        get: operations["sources_health_api_sources_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness only -- no data, no auth.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Action */
        Action: {
            /** Notes */
            notes: string;
            /**
             * Status
             * @description this user's status; legacy imports may say 'actioned'
             */
            status: string;
        };
        /** ActionPatch */
        ActionPatch: {
            /** Notes */
            notes?: string | null;
            /** Status */
            status?: ("new" | "saved" | "applied" | "interview" | "offer" | "rejected" | "ignored") | null;
        };
        /** AuthResult */
        AuthResult: {
            me: components["schemas"]["Me"];
            /**
             * Token
             * @description send as 'Authorization: Bearer <token>'; shown once, kept only as a hash
             */
            token: string;
        };
        /** CompanyConfig */
        CompanyConfig: {
            /**
             * Ats
             * @description greenhouse | lever | ashby | smartrecruiters | workday
             */
            ats: string;
            /** Name */
            name: string;
            /**
             * Slug
             * @description board slug; workday: tenant.wdN/site
             */
            slug: string;
            /**
             * Tier
             * @description S | A | B | C (S/A polled every 2 min)
             * @default B
             */
            tier: string;
        };
        /** Credentials */
        Credentials: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** FeedConfig */
        FeedConfig: {
            /**
             * Kind
             * @default rss
             */
            kind: string;
            /** Url */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstagramConfig */
        InstagramConfig: {
            /**
             * Interval S
             * @default 300
             */
            interval_s: number;
            /**
             * Priority
             * @default 5
             */
            priority: number;
            /**
             * User Id
             * @description numeric id; skips the throttled profile lookup
             * @default
             */
            user_id: string;
            /** Username */
            username: string;
        };
        /** InstagramRelay */
        InstagramRelay: {
            /** Stories */
            stories: {
                [key: string]: unknown;
            }[];
            /** Username */
            username: string;
        };
        /** Login */
        Login: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** Match */
        Match: {
            /**
             * Ok
             * @description would alert this user (the same rule the phone uses)
             */
            ok: boolean;
            /** Reasons */
            reasons: string[];
        };
        /** Me */
        Me: {
            /**
             * Account
             * @description made through sign-up (kept in the database), not listed in users.yaml
             * @default false
             */
            account: boolean;
            /**
             * Alerts Enabled
             * @description a delivery channel is configured; device receipt is not verified
             */
            alerts_enabled: boolean;
            /**
             * Guest
             * @description true for a visitor who is not logged in: read-only, default profile
             * @default false
             */
            guest: boolean;
            /**
             * Notification Url
             * @description this user's private ntfy subscription URL; no API token
             */
            notification_url: string | null;
            /** Sources */
            sources: number;
            /** User */
            user: string;
            /**
             * Username
             * @description the name this user signs in with, if they have set one
             */
            username?: string | null;
        };
        /** Metrics */
        Metrics: {
            /**
             * Items Per Day
             * @description last 7 days, items your sources saw first that day
             */
            items_per_day: {
                [key: string]: number;
            };
            /**
             * Latency
             * @description drop latency per source, your sources only
             */
            latency: components["schemas"]["SourceLatency"][];
            /** Llm Daily Budget */
            llm_daily_budget: number;
            /**
             * Llm Tokens Today
             * @description shared by every user
             */
            llm_tokens_today: number;
        };
        /** Opportunity */
        Opportunity: {
            /** @description this user's status/notes; nobody else's */
            action: components["schemas"]["Action"] | null;
            /**
             * Backfill
             * @description already open when your sources first looked (never alerted), not a live drop
             */
            backfill: boolean;
            /** Category */
            category: string;
            /** Company */
            company: string;
            /**
             * Company Domain
             * @description the company's web domain, for its logo; None until looked up, or when no confident match
             */
            company_domain?: string | null;
            /** Deadline */
            deadline: string;
            /** First Seen */
            first_seen: string;
            /** Id */
            id: string;
            /**
             * Level
             * @description "intern", "new_grad", or "" for anything else (see radar.pipeline.roles)
             * @default
             */
            level: string;
            /**
             * Location
             * @description display form: "City, ST" in the US, "City, Country" elsewhere; "; " between several
             */
            location: string;
            /**
             * Location Raw
             * @description the place exactly as the source wrote it
             * @default
             */
            location_raw: string;
            match: components["schemas"]["Match"];
            /**
             * Pay
             * @description the pay range the posting states, e.g. "$62–$72/hr" or "$120,000–$165,000/yr"; empty when it states none
             * @default
             */
            pay: string;
            /**
             * Pay Estimate
             * @description US-wide occupation wage benchmark, only when employer pay is blank
             * @default
             */
            pay_estimate: string;
            /**
             * Pay Estimate Basis
             * @description occupation, source, vintage and percentiles behind the benchmark
             * @default
             */
            pay_estimate_basis: string;
            /** Published At */
            published_at: string | null;
            /** Role Track */
            role_track: string;
            /** Season */
            season: string;
            /**
             * Sources
             * @description this user's sources that saw it
             */
            sources: string[];
            /**
             * Status
             * @description the posting itself: New, Closed, ...
             */
            status: string;
            /** Title */
            title: string;
            /**
             * Track
             * @description Quant, Software, Finance...; "Other" when no rule matches
             * @default Other
             */
            track: string;
            /** Url */
            url: string;
        };
        /** Page */
        Page: {
            /** Items */
            items: components["schemas"]["Opportunity"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ProfileConfig */
        ProfileConfig: {
            /**
             * Company Tiers
             * @default {}
             */
            company_tiers: {
                [key: string]: string;
            };
            /**
             * Exclude
             * @description any of these in the title rules it out
             * @default []
             */
            exclude: string[];
            /**
             * Grad Year
             * @description target season year, e.g. 2027
             */
            grad_year?: number | null;
            /**
             * Keywords
             * @description ...and one of these (the level)
             * @default []
             */
            keywords: string[];
            /**
             * Locations
             * @default []
             */
            locations: string[];
            /**
             * Roles
             * @description the track: a title needs one of these...
             * @default []
             */
            roles: string[];
        };
        /** RepoConfig */
        RepoConfig: {
            /**
             * Name
             * @description owner/name
             */
            name: string;
            /**
             * Path
             * @default
             */
            path: string;
        };
        /** SourceHealth */
        SourceHealth: {
            /** Disabled */
            disabled: boolean;
            /** Fail Count */
            fail_count: number;
            /** Items 24H */
            items_24h: number;
            /** Last Error */
            last_error: string | null;
            /** Last Ok */
            last_ok: string | null;
            /** Name */
            name: string;
            /** Next Run */
            next_run: string;
            /** Running */
            running: boolean;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
        };
        /** SourceLatency */
        SourceLatency: {
            /** N */
            n: number;
            /** P50 */
            p50: number;
            /** P95 */
            p95: number;
            /** Source */
            source: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistConfig */
        WatchlistConfig: {
            /**
             * Companies
             * @default []
             */
            companies: components["schemas"]["CompanyConfig"][];
            /**
             * Feeds
             * @default []
             */
            feeds: components["schemas"]["FeedConfig"][];
            /**
             * Instagram
             * @default []
             */
            instagram: components["schemas"]["InstagramConfig"][];
            /**
             * Repos
             * @default []
             */
            repos: components["schemas"]["RepoConfig"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    alerts_disable_api_alerts_disable_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_enable_api_alerts_enable_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_test_api_alerts_test_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_credentials_api_auth_credentials_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_api_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_config_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_profile_api_config_profile_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_api_config_watchlist_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_watchlist_api_config_watchlist_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    relay_instagram_api_instagram_relay_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstagramRelay"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunities_api_opportunities_get: {
        parameters: {
            query?: {
                /** @description matches: what would alert you; all: everything your sources found */
                include?: string;
                /** @description words that each start a word in the title or company */
                q?: string | null;
                /** @description words that each start a word in the location ('seattle', 'ny') */
                location?: string | null;
                /** @description only postings whose location is confirmed US (blank and location-less 'Remote' are left out) */
                us_only?: boolean;
                company?: string | null;
                source?: string | null;
                /** @description your status; 'ignored' ones are hidden unless asked for */
                action?: string | null;
                /** @description the posting's own status (New, Open, Closed...); Closed/Expired/Not actionable are hidden unless asked for */
                status?: string | null;
                /** @description first seen at or after */
                since?: string | null;
                /** @description deadline within this many days */
                closing_within?: number | null;
                /** @description newest first by when it was posted (date-only postings count as that day; none at all falls back to found), by when your sources found it, or by company prestige (S > A > B > C tiers), newest posted within a tier */
                sort?: string;
                /** @description false: only new drops; true: only postings that were already open when your sources first looked */
                backfill?: boolean | null;
                /** @description internships or new-grad roles */
                level?: string | null;
                /** @description one of: Quant, AI / ML / Data, Hardware, Security, Product, Design, Software, Finance, Business, Other */
                track?: string | null;
                /** @description posted this many days back or less (the posting date, else a live drop's found time; undated backfill never matches) */
                posted_within?: number | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunity_api_opportunities__opp_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                opp_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_opportunity_api_opportunities__opp_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                opp_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_health_api_sources_health_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceHealth"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_stream_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE: `opportunity` (a new one in your feed) and `action` (yours changed) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
